### ISSUE TITLE
How easy would it be to turn this into a proper DooM source port?

### ISSUE THREAD

**Issue by JacobSinclair** [cristicbz/rust-doom#113]
I was wondering because it would be cool to make my own source port

**Comment by cristicbz** [comment]
A "source port" as far as I can tell, implies a port of the original Doom source code. As per the README, this repo is not based at all on the original code (instead trying to go for a more modern engine design).

So if that's what you mean, then it would be very difficult (i.e. you'd have to rewrite the whole thing, basing it off the source code).

If all you mean is how hard would it be to implement all remaining features, then the answer is: it would be straight forward but laborious. There are some big missing pieces obviously, but in the last few PR-s I've been laying a lot of the groundwork---that's why it was relatively simple to add doors, lifts etc. recently.

Hope that answers your question!

**Comment by Luke-Nukem** [comment]
Been following this project since I spotted it - very fascinating, and very insightful. Thanks for building it as OSS and sharing 👍
