### ISSUE TITLE
Need to add "fake contrast"

### ISSUE THREAD

**Issue by linguica** [cristicbz/rust-doom#32]
Hi, I just checked out this project finally, and I'm impressed at how faithful it looks! But one thing I've noticed: in Doom, all walls that are perfectly "vertical" (constant x component) are effectively brightened by 16, and all walls that are horizontal (constant y component) are darkened by the same amount. This is especially obvious in a level like E2M2 (-iwad doom.wad -l 10) where the crate maze looks pretty blah without it.

**Comment by cristicbz** [comment]
Thanks for the feedback! I'll have a look when I get back from work, but it would really help if you could post a comparison screenshot. If not don't worry, I'll try to figure it out.

**Comment by linguica** [comment]
http://doomwiki.org/wiki/Fake_contrast has two screenshots (from E2M2, coincidentally) that show the difference in appearance.

**Comment by cristicbz** [comment]
Just wanted to let you know that this issue is not forgotten! Thanks a lot for pointing it out, it's been a long time since I actually played the original game so I can certainly use someone with your knowledge!

I've been really busy at work, but now with the weekend ahead of me, I'll make sure to fix this!

**Comment by cristicbz** [comment]
Check it out---let me know if you think that's faithful to the original!

**Comment by linguica** [comment]
Looks good! Now for my next quibble...
