### ISSUE TITLE
Note about nightly usage in the README unnecessary

### ISSUE THREAD

**Issue by skade** [cristicbz/rust-doom#55]
The README goes some length to explain the project uses nightly.
https://github.com/cristicbz/rust-doom#build-instructions

Safe for triggering a cargo bug (which can be easily avoided using a recent cargo build) the project builds and runs very fine on stable, though!
https://github.com/rust-lang/cargo/issues/2051

This project is actually a nice example of what stable Rust can do! And with Rust 1.4.0 just being literally hours away, the cargo issue will also vanish.

**Comment by cristicbz** [comment]
You're right! I replied on the rust subreddit too; the README only mentions that because it was written in like Oct 2014, waaay before there was a rust stable. All I meant at the time is that the code is up to date enought that it should run on whatever compiler you've got. I'll update the README when I get a chance, although I also accept PRs! :)

BTW, compiling on stable was an concious effort after May 15 and Travis runs tests on all trains---so it's no coincidence it runs on stable :P

**Comment by cristicbz** [comment]
I think I adressed your concern, let me know if it looks reasonable, I never know how to write these things.
